<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
    use douggonsouza\logged\models\user;
    use douggonsouza\logged\logged;
    use douggonsouza\permission\permission;

    $user = new user((int) logged::getId());
    $perfil = $user->perfil();
    $avatar = "/images/icon/avatar-big-01.jpg";
    $name = $user->getField('name');
    $lastName = $user->lastName();

    // views permissions
    $views = permission::permissions()::pages((int) $perfil['paper_id']);
?>
        <!-- MENU SIDEBAR -->
		<aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="<?= router::assets("/images/icon/logo-douggs.png", assets::ABSOLUTE_URL) ?>" alt="DouggS" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1" id="sidebar">
                <?php
                    if(isset($views)){
                ?>
                <ul class="nav flex-column flex-nowrap overflow-hidden">
                <?php
                    $mnName = null;
                    foreach($views as $view){
                        $li = '';
                        if($view['mn_name'] != $mnName && $mnName != null){
                            $li = '
                            <\ul>
                        <\div>
                    </li>
                    <li class="nav-item has-sub">
                        <a class="nav-link collapsed text-truncate" href="#submenu' . $view['sequence_id'] . '" data-toggle="collapse" data-target="#submenu' . $view['sequence_id'] . '"><i class="' . $view['mn_icon'] . '"></i> <span class="d-none d-sm-inline">' . router::label($view['mn_name']) . '</span></a>
                        <div class="collapse" id="submenu' . $view['sequence_id'] . '" aria-expanded="false">
                            <ul class="flex-column pl-2">';
                        }
                        if($mnName == null){
                            $li = '
                <li class="nav-item has-sub">
                    <a class="nav-link collapsed text-truncate" href="#submenu' . $view['sequence_id'] . '" data-toggle="collapse" data-target="#submenu' . $view['sequence_id'] . '"><i class="' . $view['mn_icon'] . '"></i> <span class="d-none d-sm-inline">' . router::label($view['mn_name']) . '</span></a>
                    <div class="collapse" id="submenu' . $view['sequence_id'] . '" aria-expanded="false">
                        <ul class="flex-column pl-2">';
                        } 
                        echo($li);                  
                        echo('
                                <li class="nav-item">
                                    <a class="nav-link p-1 text-truncate" href="'. router::getUsages()->getHost(). $view['url'] . '">' . router::label($view['p_name']) . '</a>
                                </li>
                        ');
                        $mnName = $view['mn_name'];
                    }
                    echo('
                            </ul>
                        </div>
                    </li>
                    ');
                    ?>
                </ul>
                <?php
                    }
                ?>
            </div>
        </aside>